### ISSUE TITLE
Info missing from Quickstart notes

### ISSUE THREAD

**Issue by ioolkos** [narioinc/vmqadmin-ui#1]
Tried to set this up as per your quick start notes.
There seems to be some information missing. After starting, the page hangs at http://localhost:7777/init/welcome.

I imagine there has to be some way of adding an VerneMQ API key, as a first step. (or maybe an admin user?)

**Comment by narioinc** [comment]
Hi ioolkos,

Thanks, my first bug :) !! Hahaha. And a grave miss on the documentation
from my end. I'll create a quick change to the docs. I was mostly sure that
the UI will pop up ask for that workflow but it seems it is broken.

I'll take a look and clear it up. You are correct on your assumption !!

When we first launch the app, the app is supposed to ask a admin api key
created using the vmq-admin api and then store that in the sqlite DB and
then use that for any further operations.

Once I fix, I'll send out the notification to you for getting the UI up and
running.

Regards,
Naresh K

**Comment by narioinc** [comment]
The latest commit fixes this bug. you should now see a welcome page that asks you for a vmq-admin api-key
while my services validates this key before moving to the next screen, but it doesnt show a UI error for now (feature to be added) if the key is not valid (API level check and not just key format check)
will add that in the next commit as "must-have".

**Comment by narioinc** [comment]
Also updated the docs :) Please check and if it runs, I can close the issue

**Comment by ioolkos** [comment]
Yes, could add an API key & after a restart of the UI I can see it can query the broker!

**Comment by narioinc** [comment]
thanks @ioolkos will close this issue
